todoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from todoapp.views import *
from.import views

app_name="todoapp"

urlpatterns = [
    path('login/',views.login,name='login'),
    path('user_login/',views.user_login,name='user_login'),
    path('user_applogin/',views.LoginPage.as_view(),name='user_applogin'),
    path('user_todo/',views.ToDo.as_view(),name='user_todo'),
    path('todo_insert/',views.TaskInsert.as_view(),name='user_todo'),
    path('user_logout/',views.Logout.as_view(),name='user_logout'),
    path('todoinsert/',views.todoinsert,name='todoinsert'),
    path('viewtodo/',views.viewtodo,name='viewtodo'),
    path('todo_delete/',views.todo_delete,name='todo_delete'),
    path('todo_logout/',views.todo_logout,name='todo_logout'),
    path('todo_view/',views.todo_view,name='todo_view'),
    path('todo_update/',views.todo_update,name='todo_update'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]

templates/loginPage.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
	<title></title>
	<style type="text/css">
		.gradient-custom-2 {
/* fallback for old browsers */
 background-image: url('/static/todo.jpg');

/* Chrome 10-25, Safari 5.1-6 */
background: -webkit-linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593);

/* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

}

@media (min-width: 768px) {
.gradient-form {
height: 100vh !important;
}
}
@media (min-width: 769px) {
.gradient-custom-2 {
border-top-right-radius: .3rem;
border-bottom-right-radius: .3rem;
}
}
	</style>
</head>
<body>
<section class="h-100 gradient-form" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
            <div class="col-lg-6">
              <div class="card-body p-md-5 mx-md-4">

                <div class="text-center">
                 
                  <h4 class="mt-1 mb-5 pb-1">LOGIN</h4>
                </div>

              
  <form action="{% url 'todoapp:user_login' %}" method= 'POST'>
              {% csrf_token %}
                 <!--  <p>Please login to your account</p> -->

                  <div data-mdb-input-init class="form-outline mb-4" >
                    <input type="text" id="form2Example11" class="form-control"
                      placeholder="Username" / name="username">
                  
                  </div>

                  <div data-mdb-input-init class="form-outline mb-4">
                    <input type="password" id="form2Example22" class="form-control" / placeholder="Password" name="password">
                  </div>

                  <div class="text-center pt-1 mb-5 pb-1">
                     <button class="btn btn-primary">LOGIN</button>
                    
                  </div>

                 <!--  <div class="d-flex align-items-center justify-content-center pb-4">
                    <p class="mb-0 me-2">Don't have an account?</p>
                    <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-danger">Create new</button>
                  </div> -->

                </form>

              </div>
            </div>
            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
              <div class="text-white px-3 py-4 p-md-5 mx-md-4">
               <!--  <h4 class="mb-4">We are more than just a company</h4>
                <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                  exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>